name: macOS 11

on: [push]

jobs:
  macos:
    name: macOS
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
    - name: Build
      run: swift build -Xswiftc -warnings-as-errors
